### ISSUE TITLE
comparison with http-shutdown

### ISSUE THREAD

**Issue by albanm** [LuKks/graceful-http#1]
Hello,

I was wondering if maybe you could provide some element of comparison with other modules that tackle the same problem. In particular I see [http-shutdown](https://github.com/thedillonb/http-shutdown) that looks pretty similar. Is there some more corner cases that are better covered by graceful-http ?

Also can you tell me what level of confidence you have that this module is production ready ?

**Comment by LuKks** [comment]
The library that you mentioned seems really old, has fewer tests, and seems to be missing some features/options. Of course, highly apprecieted any open-source libraries that tries to solve issues. In the past I also did a library like this that also didn't work properly for all cases: [like-server](https://github.com/LuKks/like-server)

This is the main difference, and this is what truly achieves a graceful http server close:
https://github.com/LuKks/graceful-http/blob/d74cdcb42e1719a7b7ad21ba7c752d3aa72200ef/index.js#L49
Besides other tweaks, but that header is the most important part.

**Comment by LuKks** [comment]
Also, read this blog, which is the only one that I found that explains the problem and solution perfectly: https://blog.dashlane.com/implementing-nodejs-http-graceful-shutdown/

That is the source of the code, besides I added more things, tests, etc.

**Comment by albanm** [comment]
Thanks. In the meantime I found this module that looks pretty good too [http-terminator](https://github.com/gajus/http-terminator). I think this one properly closes the connection as you do.

**Comment by LuKks** [comment]
Cool, closing then
